#!/bin/bash
set -euxo pipefail

[ -f /etc/jitsi-env.conf ] && source /etc/jitsi-env.conf

exec /usr/local/bin/gosu jicofo /usr/share/jicofo/jicofo.sh \
	--host=$JICOFO_HOST \
	--domain=$JICOFO_HOSTNAME \
	--secret=$JICOFO_SECRET \
	--user_name=$JICOFO_AUTH_USER \
	--user_domain=$JICOFO_AUTH_DOMAIN \
	--user_password=$JICOFO_AUTH_PASSWORD
